In [1]:
import numpy as np, pandas as pd, seaborn as sns, matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('advertising.csv')
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
X = df.drop('Sales',1)
y = df['Sales']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 0 )

In [6]:
X_train.head()

TV  Radio  Newspaper
131  265.2    2.9       43.0
96   197.6    3.5        5.9
181  218.5    5.4       27.4
19   147.3   23.9       19.1
153  171.3   39.7       37.7

In [7]:
y_train.head()

131    17.7
96     16.7
181    17.2
19     14.6
153    16.0
Name: Sales, dtype: float64

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler1 = StandardScaler()
scaler2 = StandardScaler()

In [10]:
y_train = y_train.values.reshape(-1,1)
y_test = y_test.values.reshape(-1,1)

In [11]:
X_train_sc = scaler1.fit_transform(X_train)
y_train_sc = scaler2.fit_transform(y_train)

In [12]:
X_test_sc = scaler1.transform(X_test)
y_test_sc = scaler2.transform(y_test)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
m = LinearRegression()

In [15]:
m.fit(X_train_sc, y_train_sc)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
m.score(X_train_sc, y_train_sc)

0.9159933497916114

In [17]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [18]:
y_train_pred = m.predict(X_train_sc)
y_test_pred = m.predict(X_test_sc)

In [19]:
print(r2_score(y_train_sc, y_train_pred))
print(r2_score(y_test_sc, y_test_pred))

0.9159933497916115
0.869205273491013


In [20]:
print(mean_squared_error(y_train_sc, y_train_pred))
print(mean_squared_error(y_test_sc, y_test_pred))

0.08400665020838853
0.1504948225273052


In [21]:
print(mean_absolute_error(y_train_sc, y_train_pred))
print(mean_absolute_error(y_test_sc, y_test_pred))

0.2298085274998129
0.2670830595941502


In [22]:
m.coef_

array([[0.87999755, 0.32972082, 0.00822756]])

In [23]:
m.intercept_

array([-1.43638836e-16])

In [24]:
m.predict([[1,1,1]])

array([[1.21794593]])

In [25]:
m.intercept_ + 0.87999755 + 0.32972082 + 0.00822756

array([1.21794593])

In [26]:
scaler2.inverse_transform(m.predict(scaler1.transform([[1,1,1]])))

array([[4.83566497]])